<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        let name="Sandeep"
        let n =My name is ${name}
        console.log(n);

        let coffee=5;
        let bagals=3;
        let soup=9;
        let cost = coffee+(2*bagals)+soup

        let n1=cost of your food:${cost}
        console.log(n1);

        let tax=cost*0.1;

        let n3=tax(10%):${tax}
        console.log(n3);

        let totalcost=cost+tax;
        let n4=Totalcost :${totalcost}
        console.log(n4);

        
    </script>
</body>
</html>
